### ISSUE TITLE
Directory mismatch on unix hosted machines

### ISSUE THREAD

**Issue by kubawolanin** [choffmeister/roboto-fontface-bower#34]
Hello!
Thank you for creating this package!
I stumbled upon an issue, though.
Fonts are stored in `/roboto-fontface/fonts/roboto` - notice the small case.

However, the Scss files try to import fonts from `/Roboto/`.
This causes an issue when user tries to load resource from the `/roboto/` catalogue which doesn't exist.

**Comment by choffmeister** [comment]
Thanks. Is this issue still relevant? The font files are like https://github.com/choffmeister/roboto-fontface-bower/blob/master/fonts/Roboto/Roboto-Black.eot

Are you on the must recent version?

**Comment by sunrenjie** [comment]
@choffmeister I hit precisely this problem today.
The current version available from bower (as someone would get by casually typing "bower install roboto-fontface") is 0.5.0, and it is effectively broken because of this.
Would you please kindly push the current version to bower?

Also, I think the bower.json file needs updates on the fonts dir too, for the sake of completeness.

Thanks.

**Comment by choffmeister** [comment]
@sunrenjie Ahh, sorry. I did forget to tag the commit so that bower picks it up. Version `0.6.0` with the fix should now also be available via bower. Please check if this fixes the issue for you.

**Comment by choffmeister** [comment]
@kubawolanin Did you also fetched the package via bower? If so, please also check if upgrading to `0.6.0` solves this issue for you.

**Comment by sunrenjie** [comment]
@choffmeister Well, my problems are all gone after updating. This is amazing fast and awesome!

Thanks.

**Comment by choffmeister** [comment]
I will consider this fixed.
