### ISSUE TITLE
Add font-display: auto;

### ISSUE THREAD

**Issue by tracker1** [choffmeister/roboto-fontface-bower#58]
Add `font-display: auto;` to the css files, so that the browser will display a fallback font while loading.

**Comment by jschroeter** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display), `auto` is the default value, so it doesn't need to be set?

**Comment by tracker1** [comment]
I'm getting errors via the Audits on chrome's developer tools related to this. (and the text is not visible until the actual font loads, where it would be good to see a fallback font here).

**Comment by choffmeister** [comment]
@tracker1 Sorry for the long delay, I am not really working on this repo anymore.

I would not want to add this to the CSS of this font package. The decision should be up to the user of this package. So if you want a specific `font-display`, you should just set it in your custom CSS.

Side note: You chrome audit warning should not go away with `font-display: auto`, because as @jschroeter pointed out this is the default anyway. Using `font-display: fallback` should help though.
