### ISSUE TITLE
The fontface path is /font and should be ../font

### ISSUE THREAD

**Issue by pwnjack** [choffmeister/roboto-fontface-bower#7]
As stated, when installing the package via Bower the fontface path points to font/path-to-font-file while usually the fontface css file is inside the css folder, so it should be ../font/path-to-font-file.

Just saying.

**Comment by UzEE** [comment]
I've also run into a similar issue. I'm using ```grunt``` and ```bower``` in my build system and my structure is like

```
root/
|__scripts/
|__styles/
|__fonts/
|__images/
|__views/
|__index.html
```

All existing packages I'm using (bootstrap, font-awesome, winjs etc.) follow the convention of including the font from ```../fonts/``` instead of ```fonts/``` like this package is doing. They all generally structure their bower package internally as follows:

```
root/
|__bower_components/
   |__font-awesome/
      |__css/
      |  |__style files.css
      |__js/
      |  |__script files.css
      |__...
      |__fonts/
      |  |__font files.ttf
      |__...
      |__bower.json
```

The build system (```grunt```) in this case is setup to copy font files from the ```bower_components/package/fonts/...``` directory to ```dist/fonts/...``` directory, and everything fine. In ```roboto-fontface``` case however, the css files look for the fonts in ```dist/styles/fonts/...``` instead which don't exist.
